function outMat = delayandsum3D(fileroot, c, omega)
% Convolve a source timeseries with the channel impulse response to
% get the received waveform.
%
% This is a delay-and-sum process in which echoes of the source waveform
% are combined based on their amplitude and arrival time
%
% mbp 8/96, Universidade do Algarve
% 4/09 addition of Doppler effects
%
% [input]
%   c - reduction velocity (should exceed fastest possible arrival)
%
% [MODIFICATIONS]
%   LA - made the script as a function. range replaces by r
%
% LA - MAR 2025


v   = [ 0, 0 ];   % Receiver motion vector (vr, vz ) in m/s
c0  = 1500;       % reference speed to convert v to proportional Doppler

T   = 2.0;           % time window to capture - this is the recording lenght
sample_rate = 1000; % this is the sample rate in time related to T.

Narrmx  = 100;
% isd     = 1;   % source depth index

% generated by 'cans'
TStart      = -1;
TEnd        =  2;
t_sts       = linspace( TStart, TEnd, ( TEnd - TStart ) * sample_rate )';
Pulse       = 'P';
[ sts, PulseTitle ] = cans( t_sts, omega, Pulse ); %important function, cans

% normalize the source time series so that it has 0 dB source level
% (measured based on the peak power in the timeseries)
sts = -sts / max( abs( sts ) );   % the - is to match other AT models
nsts = length( sts );   % number of samples in the source time series

%%

% optional Doppler effects
% pre-calculate Dopplerized versions of the source time series
% following can be further optimized if we know that ray-angle limits
% further restrict possible Doppler factors

if ( norm( v ) > 0 )
    disp( 'Setting up Dopplerized waveforms' )
    %v_vec = linspace( min( v ), max( v ), 10 );     % vector of Doppler velocity bins
    v_vec       = linspace( 1.9, 2, 51 );            % vector of Doppler velocity bins
    alpha_vec   = 1 - v_vec / c0;                    % Doppler factors
    nalpha      = length( alpha_vec );
    sts_hilbert = zeros( nsts, nalpha );

    % loop over Doppler factors (should be further vectorized ...)
    for ialpha = 1 : length( alpha_vec )
        disp( ialpha )
        sts_hilbert( :, ialpha ) = hilbert( arbitrary_alpha( sts', alpha_vec( ialpha ) )' ); % Dopplerize
    end
else
    sts_hilbert = hilbert( sts );   % need the Hilbert transform for phase changes (imag. part of amp)
    % sts_hilbert = sts;
end
%%
% Main routine:
% read the arrivals file and convolve with the source waveform

ARRFIL   = [ fileroot '.arr' ];

[ Arr, Pos ] = read_arrivals_asc( ARRFIL );  % read the arrivals file
disp( 'Done reading arrivals')
omega = 2 * pi * Pos.freq;

% select which source/receiver index to use
nsd = length( Pos.s.z );
nrr = length( Pos.r.r );
nrd = length( Pos.r.z );
ntheta = length (Pos.r.theta);

outMat = cell(1, ntheta);


deltat = 1 / sample_rate;
nrts   = round( T / deltat );	  % number of samples in the receiver time series
disp(nrts);

for itheta = 1 : ntheta % loop over receiver angles

    outMat{1, itheta} = zeros( nrts, nrd, nrr); % to store sum over number of sources. 

    rtsmat= zeros( nrts, nrd, nrr); % temporary variable

    for isd = 1: nsd
        for ird = 1 : nrd   % loop over receiver depths
            disp( ird )

            for irr = 1 : nrr   % loop over receiver ranges
                tstart = Pos.r.r( irr ) / c - 0.1;   % min( delay( ir, :, ird ) )

                % compute channel transfer function

                rts = zeros( nrts, 1 );	% initialize the time series

                Narr = Arr( irr, ird, itheta).Narr;

                for iarr = 1 : Narr   % loop over arrivals

                    % delay is a complex value with the imaginary part holding loss due to volume attenuation
                    % Thus, e( -i omega * delay ) has a phase delay and an amplitude decay.
                    % Need to check that omega is a central frequency and test the VolumeLoss

                    Tarr = real( Arr( irr, ird, itheta ).delay( iarr ) ) - tstart;   % arrival time relative to tstart
                    VolumeLoss = exp( omega * imag( Arr( irr, ird, itheta ).delay( iarr ) ) );

                    irts1 = round( Tarr / deltat + 1 );            % starting time index in rts for that delay
                    irts2 = irts1 + nsts - 1;                      % ending   time index in rts
                    ists1 = 1;                                      % starting time index in sts
                    ists2 = nsts;                                   % ending   time index in sts

                    % clip to make sure [ it1, it2 ] is inside the limits of rts
                    if ( irts1 < 1 )
                        ists1 = ists1 + ( 1 - irts1 );  % shift right by 1 - it1 samples
                        irts1  = 1;
                    end

                    if ( irts2 > nrts )
                        ists2 = ists2 - ( irts2 - nrts );  % shift left by it2 - nt samples
                        irts2  = nrts;
                    end

                    if ( norm( v ) > 0 )
                        % identify the Doppler bin
                        theta_ray = Arr( irr, ird, itheta ).RcvrDeclAngle( iarr ) * pi / 180;   % convert ray angle to radians
                        tan_ray   = [ cos( theta_ray ) sin( theta_ray ) ];        % form unit tangent
                        alpha     = 1 - dot( v / c0, tan_ray );                   % project Doppler vector onto ray tangent
                        ialpha    = 1 + round( ( alpha - alpha_vec( 1 ) ) / ( alpha_vec( end ) - alpha_vec( 1 ) ) * ( length( alpha_vec ) - 1 ) );

                        % check alpha index within bounds?
                        if ( ialpha < 1 || ialpha > nalpha )
                            disp( 'Doppler exceeds pre-tabulated values' )
                            ialpha = max( ialpha, 1 );
                            ialpha = min( ialpha, nalpha );
                        end

                        % load the weighted and Dopplerized waveform into the received time series
                        rts( irts1 : irts2 ) = rts( irts1 : irts2 ) + VolumeLoss * ...
                            real( Arr( irr, ird, itheta ).A( iarr ) * sts_hilbert( ists1 : ists2, ialpha ) );
                    else

                        % rts( it1 : it2 ) = rts( it1 : it2 ) + real( Arr( irr, ird, isd ).A( iarr ) ) * real( sts_hilbert( its1 : its2, 1 ) ) ...
                        %                                     - imag( Arr( irr, ird, isd ).A( iarr ) ) * imag( sts_hilbert( its1 : its2, 1 ) );

                        % following is math-equivalent to above, but runs faster in
                        % Matlab even though it looks like more work ...
                        rts( irts1 : irts2 ) = rts( irts1 : irts2 ) + VolumeLoss * ...
                            real( Arr( irr, ird, itheta ).A( iarr ) * sts_hilbert( ists1 : ists2, 1 ) );
                    end
                end   % next arrival, iarr

                %wavwrite( 0.95 * rts / max( abs( rts ) ) , sample_rate, [ 'rts_Rd_' num2str( ird ) '_Rr_' num2str( ir ) '.wav' ] );
                %rtsmat( :, ir ) = 0.95 * rts / max( abs( rts ) );
                rtsmat( :, ird, irr) = rts;
            end
            %eval( [ ' save ' fileroot '_Rd_' num2str( ird ) ' rtsmat Pos sample_rate' ] );
        end
        outMat{1, itheta} = outMat{1, itheta} + rtsmat;
    end
end
ll = 0;
%%
%plot snapshots
%nt =2;
%figure
%for it = 1 : nt
%   imagesc( squeeze( rtsmat( it, :, : ) ) )
%   colorbar
%   drawnow
%end

%%
% save to a Matlab timeseries file